# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 09:44
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0004_auto_20190213_0944'),
        ('js_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='related',
        ),
        migrations.AddField(
            model_name='event',
            name='services',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_services.Service', verbose_name='services'),
        ),
    ]
