# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_icon.fields
import filer.fields.image
import js_events.models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_categories', '0007_categorytranslation_landing_page'),
        ('js_services', '0004_auto_20190213_0944'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_people', '0026_person_services'),
        ('js_events', '0002_auto_20190213_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRelatedPlugin',
            fields=[
                ('cache_duration', models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached.")),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('icon', djangocms_icon.fields.Icon(blank=True, default='fa-', max_length=255, verbose_name='Icon')),
                ('number_of_items', models.PositiveSmallIntegerField(verbose_name='Number of events')),
                ('layout', models.CharField(max_length=30, verbose_name='layout')),
                ('time_period', models.CharField(max_length=30, verbose_name='Time Period')),
                ('featured', models.BooleanField(default=False)),
                ('exclude_current_item', models.BooleanField(default=False, verbose_name='Exclude current event')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_events_title_image', to=settings.FILER_IMAGE_MODEL)),
                ('related_categories', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_categories.Category', verbose_name='related categories')),
                ('related_hosts', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_people.Person', verbose_name='related hosts')),
                ('related_services', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_services.Service', verbose_name='related services')),
                ('related_types', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_events.EventsConfig', verbose_name='related sections')),
            ],
            options={
                'abstract': False,
            },
            bases=(js_events.models.PluginEditModeMixin, 'cms.cmsplugin', models.Model),
        ),
    ]
