# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0004_auto_20190213_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event end'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event start'),
        ),
    ]
