# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 05:21
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        #('js_companies', '0001_initial'),
        ('js_events', '0007_remove_event_city'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='event',
            #name='companies',
            #field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_companies.Company', verbose_name='companies'),
        #),
    ]
