# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 17:05
from __future__ import unicode_literals

from django.db import migrations
import djangocms_icon.fields

def forwards(apps, schema_editor):
    EventRelatedPlugin = apps.get_model('js_events', 'EventRelatedPlugin')
    for s in EventRelatedPlugin.objects.all():
        if s.icon == 'fa-':
            s.icon = ''
            s.save()

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0008_event_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='icon',
            field=djangocms_icon.fields.Icon(blank=True, default='', max_length=255, verbose_name='Icon'),
        ),
        migrations.RunPython(forwards, backward),
    ]
