# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0009_auto_20190429_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='companies',
        ),
    ]
