# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('js_events', '0010_remove_event_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', help_text="Provide this speaker's first name.", max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(default='', help_text="Provide this speaker's last name.", max_length=255, verbose_name='last name')),
                ('suffix', models.CharField(blank=True, default='', help_text="Provide this speaker's suffix.", max_length=60, verbose_name='suffix')),
                ('slug', models.SlugField(blank=True, default='', help_text='Leave blank to auto-generate a unique slug.', max_length=255, verbose_name='unique slug')),
                ('company', models.CharField(blank=True, default='', help_text="Provide this speaker's company.", max_length=255, verbose_name='company')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='description')),
                ('is_published', models.BooleanField(default=True, verbose_name='show on website')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='mobile')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('second_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='secondary phone')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='fax')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin')),
                ('visual', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
    ]
