# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0011_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_event',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Hero Event'),
        ),
    ]
