# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0012_event_hero_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='redirect_url',
            field=models.CharField(blank=True, default='', help_text='when this value is filled in the Event page does not load, it redirects to the entered url', max_length=255, verbose_name='Redirect URL'),
        ),
    ]
