# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0013_event_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='function',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='role'),
        ),
    ]
