# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0017_auto_20190607_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_text',
            field=models.CharField(blank=True, default='', help_text='Text to appear on either the Registration Link or External Link', max_length=255, verbose_name='Link Text'),
        ),
    ]
