# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 15:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import parler.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_locations', '0007_auto_20190709_2309'),
        ('js_events', '0020_auto_20190712_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_start']},
        ),
        migrations.AddField(
            model_name='event',
            name='locations',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_locations.Location', verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='eventsconfigtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='js_events.EventsConfig'),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='js_events.Event'),
        ),
    ]
