# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 18:11
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_locations', '0007_auto_20190709_2309'),
        ('js_events', '0021_auto_20190729_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrelatedplugin',
            name='related_locations',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_locations.Location', verbose_name='related locations'),
        ),
    ]
