# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0022_eventrelatedplugin_related_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtranslation',
            name='display_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Display Location'),
        ),
    ]
