# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0025_create_placeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsconfig',
            name='allow_post',
            field=models.BooleanField(default=False, verbose_name='Allow POST requests'),
        ),
    ]
