# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 12:52
from __future__ import unicode_literals

import aldryn_common.admin_fields.sortedm2m
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_icon.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('js_events', '0026_eventsconfig_allow_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedSpeakersPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('icon', djangocms_icon.fields.Icon(blank=True, default='', max_length=255, verbose_name='Icon')),
                ('number_of_people', models.PositiveSmallIntegerField(verbose_name='Number of people')),
                ('layout', models.CharField(blank=True, default='', max_length=30, verbose_name='layout')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_speakers', to=settings.FILER_IMAGE_MODEL)),
                ('speakers', aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='js_events.Speaker', verbose_name='speakers')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='js_locations.Location', verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='event',
            name='services',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='js_services.Service', verbose_name='services'),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='related_categories',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='aldryn_categories.Category', verbose_name='related categories'),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='related_hosts',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='aldryn_people.Person', verbose_name='related hosts'),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='related_locations',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='js_locations.Location', verbose_name='related locations'),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='related_services',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='js_services.Service', verbose_name='related services'),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='related_types',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='js_events.EventsConfig', verbose_name='related sections'),
        ),
    ]
