# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0028_auto_20191025_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Event template'),
        ),
    ]
