# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0030_auto_20191114_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='layout'),
        ),
    ]
