# Generated by Django 2.2.9 on 2020-01-28 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0032_eventsconfig_show_in_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aldryn_people.Person', verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_2', to='aldryn_people.Person', verbose_name='second host'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_3', to='aldryn_people.Person', verbose_name='third host'),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='exclude_current_item',
            field=models.BooleanField(blank=True, default=False, verbose_name='Exclude current event'),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events_title_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='eventrelatedplugin',
            name='more_button_is_shown',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show “See More Button”'),
        ),
        migrations.AlterField(
            model_name='relatedspeakersplugin',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_speakers', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
