# Generated by Django 2.2.13 on 2020-06-25 11:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0033_auto_20200128_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsconfig',
            name='custom_fields_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
