# Generated by Django 2.2.13 on 2020-08-14 09:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0034_auto_20200625_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsconfig',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
