# Generated by Django 2.2.10 on 2020-11-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0035_eventsconfig_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtranslation',
            name='is_featured_trans',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is featured'),
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='is_published_trans',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is published'),
        ),
    ]
