# Generated by Django 2.2.19 on 2021-04-13 13:15

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0021_auto_20201209_0933'),
        ('js_events', '0038_auto_20210312_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrelatedplugin',
            name='related_service_sections',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_services.ServicesConfig', verbose_name='related service section'),
        ),
    ]
