# Generated by Django 2.2.24 on 2022-02-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0040_event_related_articles_placeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_start', 'id']},
        ),
        migrations.AddField(
            model_name='eventsconfig',
            name='dates_required',
            field=models.BooleanField(default=True, verbose_name='Dates are required'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event start'),
        ),
    ]
