# Generated by Django 2.2.24 on 2022-02-04 11:19

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('js_events', '0041_auto_20220203_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_banner',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_event_banner', slotname='Event banner', to='cms.Placeholder'),
        ),
    ]
