# Generated by Django 2.2.24 on 2022-04-14 12:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_events', '0042_event_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtranslation',
            name='custom_fields_trans',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
